:- module(guardrails, [
    validate_portfolio_json/2
]).

:- use_module(library(http/json)).

/** <module> Financial Guardrails Module
 *
 * Validates investment recommendations generated by LLMs using
     symbolic rules.
 * Input is a JSON string representing the recommendation:
 * {
 *   "client_age": 70,
 *   "risk_tolerance": "low",
 *   "allocations": {
 *     "stocks": 20,
 *     "bonds": 50,
 *     "crypto": 10,
 *     "cash": 20
 *   }
 * }
 */

% Main entry point. Parses JSON and checks all policy rules.
% Returns a list of error atoms. If empty, the portfolio is valid.
validate_portfolio_json(JsonString, Errors) :-
    setup_call_cleanup(
        open_string(JsonString, Stream),
        json_read_dict(Stream, Dict),
        close(Stream)
    ),
    findall(Error, check_policy(Dict, Error), Errors).

% --- Policy Rules ---

% 1. Total sum must be exactly 100%
check_policy(Dict, "Total allocation must sum to exactly 100%") :-
    get_allocations(Dict, Stocks, Bonds, Crypto, Cash),
    Total is Stocks + Bonds + Crypto + Cash,
    Total \= 100.

% 2. If client is senior (> 65), high-risk assets (stocks + crypto) must
% be <= 30%
check_policy(Dict, Error) :-
    Age = Dict.get(client_age),
    Age > 65,
    get_allocations(Dict, Stocks, _, Crypto, _),
    HighRiskAllocation is Stocks + Crypto,
    HighRiskAllocation > 30,
    format(string(Error),
        "Senior client (age ~w) has ~w% in high-risk assets (max: 30%)",
            [Age, HighRiskAllocation]).

% 3. If risk tolerance is 'low', crypto allocation must be 0%
check_policy(Dict,





                        "Low risk tolerance portfolio cannot contain speculative crypto assets") :-
    Risk = Dict.get(risk_tolerance),
    Risk == "low", % json_read_dict parses strings as SWI-Prolog string
                   % terms or atoms depending on settings
    get_allocations(Dict, _, _, Crypto, _),
    Crypto > 0.

% 4. If risk tolerance is 'low', conservative assets (bonds + cash) must
% be >= 50%
check_policy(Dict, Error) :-
    Risk = Dict.get(risk_tolerance),
    Risk == "low",
    get_allocations(Dict, _, Bonds, _, Cash),
    Conservative is Bonds + Cash,
    Conservative < 50,
    format(string(Error),





                            "Low risk tolerance requires at least 50% in conservative assets (currently ~w%)", [Conservative]).

% 5. No asset allocation can be negative
check_policy(Dict, "Asset allocations cannot be negative") :-
    get_allocations(Dict, Stocks, Bonds, Crypto, Cash),
    (Stocks < 0 ; Bonds < 0 ; Crypto < 0 ; Cash < 0).

% --- Helper to extract allocations safely with default 0 if missing ---
get_allocations(Dict, Stocks, Bonds, Crypto, Cash) :-
    Allocations = Dict.get(allocations),
    Stocks = Allocations.get(stocks, 0),
    Bonds = Allocations.get(bonds, 0),
    Crypto = Allocations.get(crypto, 0),
    Cash = Allocations.get(cash, 0).
