:- module(guardrails, [
    validate_portfolio_json/2
]).

:- use_module(library(http/json)).

/** <module> Financial Guardrails Module
 *
 * Validates investment recommendations generated by LLMs using
 * symbolic rules.
 * Input is a JSON string representing the recommendation:
 * {
 *   "client_age": 70,
 *   "risk_tolerance": "low",
 *   "allocations": {
 *     "stocks": 20,
 *     "bonds": 50,
 *     "crypto": 10,
 *     "cash": 20
 *   }
 * }
 */

% Main entry point. Parses JSON and checks all policy rules.
% Returns a list of error atoms. If empty, the portfolio is valid.
validate_portfolio_json(JsonString, Errors) :-
    setup_call_cleanup(
        open_string(JsonString, Stream),
        catch(
            json_read_dict(Stream, Dict),
            JsonError,
            Dict = policy_error(JsonError)
        ),
        close(Stream)
    ),
    (   Dict = policy_error(JsonError)
    ->  message_to_string(JsonError, Msg),
        format(string(ErrStr), "Invalid JSON input: ~w", [Msg]),
        Errors = [ErrStr]
;   missing_required_keys(Dict, Missing), Missing \= []
->  atomic_list_concat(Missing, ', ', MissingStr),
        format(string(ErrStr),
            "Missing required keys in recommendation: ~w", [MissingStr]),
        Errors = [ErrStr]
    ;   findall(Error, check_policy(Dict, Error), Errors)
    ).

% Keys that every recommendation must provide. A key is "missing"
% when it is absent from the dict or its value is unbound (fresh var).
% Total: get_dict/2 can throw on absent keys, so wrapped in catch/3.
missing_required_keys(Dict, Missing) :-
    findall(Key,
        (   member(Key, [client_age, risk_tolerance, allocations]),
            \+ has_value(Dict, Key)
        ),
        Missing).

% has_value(+Dict, +Key) is semidet. Total: fails instead of throwing
% when the key is absent or the value is a fresh variable.
has_value(Dict, Key) :-
    catch(get_dict(Key, Dict, Value), _, fail),
    nonvar(Value).

% risk_value(+Dict, -RiskAtom)
% Extract risk_tolerance and canonicalise to a downcased atom, so the
% policy rules work whether the value arrived as a Prolog atom
% (json_read_dict default) or as a string (Janus / value_string_as).
% risk_value(+Dict, -RiskAtom)
% Extract risk_tolerance and canonicalise to a downcased atom, so the
% policy rules work whether the value arrived as a Prolog atom
% (json_read_dict default) or as a string (Janus / value_string_as).
risk_value(Dict, RiskAtom) :-
    has_value(Dict, risk_tolerance),
    Risk0 = Dict.get(risk_tolerance, ""),
    (   string(Risk0)
    ->  downcase_atom_(Risk0, RiskAtom)
    ;   atom(Risk0)
    ->  downcase_atom(Risk0, RiskAtom)
    ;   RiskAtom = unknown
    ).

% Small norm/2-style conversion: string -> downcased atom.
downcase_atom_(String, Atom) :-
    string_lower(String, Lower),
    atom_string(Atom, Lower).

% --- Policy Rules ---

% 1. Total sum must be exactly 100%
check_policy(Dict, "Total allocation must sum to exactly 100%") :-
    get_allocations(Dict, Stocks, Bonds, Crypto, Cash),
    Total is Stocks + Bonds + Crypto + Cash,
    Total \= 100.

% 2. If client is senior (> 65), high-risk assets (stocks + crypto) must
% be <= 30%
check_policy(Dict, Error) :-
    has_value(Dict, client_age),
    Age = Dict.get(client_age, 0),
    Age > 65,
    get_allocations(Dict, Stocks, _, Crypto, _),
    HighRiskAllocation is Stocks + Crypto,
    HighRiskAllocation > 30,
    format(string(Error),
        "Senior client (age ~w) has ~w% in high-risk assets (max: 30%)",
            [Age, HighRiskAllocation]).

% 3. If risk tolerance is 'low', crypto allocation must be 0%
check_policy(Dict,
        "Low risk tolerance portfolio cannot contain speculative crypto assets") :-
    risk_value(Dict, low),
    get_allocations(Dict, _, _, Crypto, _),
    Crypto > 0.

% 4. If risk tolerance is 'low', conservative assets (bonds + cash) must
% be >= 50%
check_policy(Dict, Error) :-
    risk_value(Dict, low),
    get_allocations(Dict, _, Bonds, _, Cash),
    Conservative is Bonds + Cash,
    Conservative < 50,
    format(string(Error),
        "Low risk tolerance requires at least 50% in conservative assets (currently ~w%)", [Conservative]).

% 5. No asset allocation can be negative
check_policy(Dict, "Asset allocations cannot be negative") :-
    get_allocations(Dict, Stocks, Bonds, Crypto, Cash),
    (Stocks < 0 ; Bonds < 0 ; Crypto < 0 ; Cash < 0).

% --- Helper to extract allocations safely with default 0 if missing ---
get_allocations(Dict, Stocks, Bonds, Crypto, Cash) :-
    (   has_value(Dict, allocations)
    ->  Allocations = Dict.get(allocations, _{})
    ;   Allocations = _{}
    ),
    Stocks = Allocations.get(stocks, 0),
    Bonds = Allocations.get(bonds, 0),
    Crypto = Allocations.get(crypto, 0),
    Cash = Allocations.get(cash, 0).
